# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  username: <%= ENV['EBALENT_DATABASE_USERNAME'] %>
  password: <%= ENV['EBALENT_DATABASE_PASSWORD'] %>


development:
  <<: *default
  database: eBalent_development

test:
  <<: *default
  database: eBalent_test

production:
  <<: *default
  database: eBalent_production
